name: Pull Request Merged
on:
  pull_request:
    branches: [main]
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send notification
      run: |
        if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
          echo "Pull request #${{ github.event.pull_request.number }} has been merged! "  
          echo "Thanks for your contribution - by Rohan Anand(repo owner)"
        fi
